# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: calibre-web
  namespace: calibre-web
spec:
  selector:
    app: calibre-web
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8083
    targetPort: 8083
