---
apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  selector:
    app: paperless-ngx
  type: ClusterIP
  ports:
  - name: paperless-ngx
    protocol: TCP
    port: 8080
    targetPort: 8080

